### ISSUE TITLE
Error when viewing the Whitepaper.

### ISSUE THREAD

**Issue by nnnnat** [orchidsource/www.orchid.com#3]
Hey y'all, I visited www.orchid.com today and when I clicked the "Read the Whitepaper" button on the home page I was met with a blank screen and this error in the browser console.

`ERROR Error: "Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'assets/whitepaper/whitepaper.pdf'`

![orchid-whitepaper-error](https://user-images.githubusercontent.com/1135948/54039406-7b35ec80-4188-11e9-8b49-9ccafcc0d6d3.png)

I'm using Firefox 65.0.1

**Comment by nhandler** [comment]
Hello @nnnnat , thank you for taking the time to not only try and read our whitepaper, but to also file an issue when it failed to load as expected. We were able to confirm and reproduce the issue, and we have deployed a fix. You should be able to access the white paper at https://www.orchid.com/assets/whitepaper/whitepaper.pdf . It is also archived in the Wayback machine at http://web.archive.org/web/20190308165135/https://www.orchid.com/assets/whitepaper/whitepaper.pdf .

Thanks again for helping to make out site better!
